_schema: _schema
paths:
  uploads: uploads
  static: ''
collections_config:
  pages:
    path: content
    name: Pages
    icon: wysiwyg
    include_developer_files: true
    description: ''
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  menu:
    path: content/menu
    name: Menu
    icon: menu
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  offers:
    path: content/offers
    name: Offers
    icon: orders
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  reviews:
    path: content/reviews
    name: Reviews
    icon: reviews
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  LINKS:
    path:
    glob:
    name:
    singular_name:
    icon: notes
    url:
    include_developer_files:
    documentation:
    description:
    preview:
    sort:
    sort_options:
    _editables:
    _enabled_editors:
    _inputs:
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
    schema_key:
timezone: Asia/Calcutta
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: false
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
